In [1]:
import pandas as pd
import os

In [2]:
df = pd.read_csv('./data/train.csv')
df.head()

,id,img_path,overview,cat1,cat2,cat3
0,TRAIN_00000,./image/train/TRAIN_00000.jpg,소안항은 조용한 섬으로 인근해안이 청정해역으로 일찍이 김 양식을 해서 높은 소득을 ...,자연,자연관광지,항구/포구
1,TRAIN_00001,./image/train/TRAIN_00001.jpg,경기도 이천시 모가면에 있는 골프장으로 대중제 18홀이다. 회원제로 개장을 했다가 ...,레포츠,육상 레포츠,골프
2,TRAIN_00002,./image/train/TRAIN_00002.jpg,금오산성숯불갈비는 한우고기만을 전문적으로 취급하고 사용하는 부식 자재 또한 유기농법...,음식,음식점,한식
3,TRAIN_00003,./image/train/TRAIN_00003.jpg,철판 위에서 요리하는 안동찜닭을 맛볼 수 있는 곳이다. 경상북도 안동시에 있는 한식...,음식,음식점,한식
4,TRAIN_00004,./image/train/TRAIN_00004.jpg,※ 영업시간 10:30 ~ 20:30\n\n3대에 걸쳐 아귀만을 전문으로 취급하는 ...,음식,음식점,한식

In [3]:
display(df['cat1'].unique())
display(df['cat2'].unique())
display(df['cat3'].unique())

array(['자연', '레포츠', '음식', '인문(문화/예술/역사)', '숙박', '쇼핑'], dtype=object)

array(['자연관광지', '육상 레포츠', '음식점', '축제', '역사관광지', '문화시설', '휴양관광지', '숙박시설',
       '공연/행사', '쇼핑', '체험관광지', '복합 레포츠', '건축/조형물', '관광자원', '수상 레포츠',
       '산업관광지', '항공 레포츠', '레포츠소개'], dtype=object)

array(['항구/포구', '골프', '한식', '야영장,오토캠핑장', '섬', '일반축제', '유적지/사적지', '일식',
       '자연휴양림', '전시관', '관광단지', '모텔', '스키(보드) 렌탈샵', '바/까페', '채식전문점',
       '한옥스테이', '컨벤션', '성', '중식', '안보관광', '전문상가', '이색거리', '해수욕장', '5일장',
       '미술관/화랑', '공원', '상설시장', '박물관', '도서관', '공연장', '농.산.어촌 체험', '복합 레포츠',
       '펜션', '산', '기념탑/기념비/전망대', '기념관', '자동차경주', '자전거하이킹', '희귀동.식물',
       '유명건물', '수목원', '유원지', '사찰', '강', '자연생태관광지', '박람회', '문화전수시설', '계곡',
       '폭포', '서양식', '종교성지', '동상', '기타행사', '고택', '국립공원', '게스트하우스', '썰매장',
       '요트', '문화원', '래프팅', '승마', '공예,공방', '트래킹', '온천/욕장/스파', '수련시설',
       '해안절경', '패밀리레스토랑', '기암괴석', '기타', '홈스테이', '민물낚시', '콘도미니엄', '민박',
       '테마공원', '유람선/잠수함관광', '바다낚시', '수영', '백화점', '호수', '카약/카누', '외국문화원',
       '면세점', '다리/대교', '카지노', '분수', '동굴', '도립공원', '윈드서핑/제트스키', '특산물판매점',
       '유스호스텔', '고궁', '서비스드레지던스', '민속마을', '전통공연', '문', '식음료', '번지점프',
       '터널', '문화관광축제', '카트', '클럽', '발전소', '대중콘서트', 'MTB', '군립공원', '스케이트',
       '대형서점', '생가', '스카이다이빙', '영화관', '헹글라이딩/패러글라이딩', '스노쿨링/스킨스쿠버다이빙',
       '약수터', '인라인(실내 인라인 포함)', '이색찜질방', '학교', '헬스투어', '등대', '사격장', 'ATV',
       '빙벽등반', '수상레포츠', '연극', '컨벤션센터', '스키/스노보드', '뮤지컬', '이색체험', '클래식음악회'],
      dtype=object)

In [4]:
display(len(df['cat1'].unique()))
display(len(df['cat2'].unique()))
display(len(df['cat3'].unique()))

6

18

128

# cat1 - cat2 연관성

In [5]:
for n_cat1 in df['cat1'].unique() :
    print("cat1 name : ", n_cat1)
    print(df[df['cat1'] == n_cat1]['cat2'].unique())
    print()

cat1 name :  자연
['자연관광지' '관광자원']

cat1 name :  레포츠
['육상 레포츠' '복합 레포츠' '수상 레포츠' '항공 레포츠' '레포츠소개']

cat1 name :  음식
['음식점']

cat1 name :  인문(문화/예술/역사)
['축제' '역사관광지' '문화시설' '휴양관광지' '공연/행사' '체험관광지' '건축/조형물' '산업관광지']

cat1 name :  숙박
['숙박시설']

cat1 name :  쇼핑
['쇼핑']

# cat2 - cat3 연관성

In [6]:
for n_cat2 in df['cat2'].unique() :
    print("cat2 name : ", n_cat2)
    print(df[df['cat2'] == n_cat2]['cat3'].unique())
    print()

cat2 name :  자연관광지
['항구/포구' '섬' '자연휴양림' '해수욕장' '산' '수목원' '강' '자연생태관광지' '계곡' '폭포' '국립공원'
 '해안절경' '호수' '동굴' '도립공원' '군립공원' '약수터' '등대']

cat2 name :  육상 레포츠
['골프' '야영장,오토캠핑장' '스키(보드) 렌탈샵' '자동차경주' '자전거하이킹' '썰매장' '승마' '트래킹' '수련시설'
 '카지노' '번지점프' '카트' 'MTB' '스케이트' '인라인(실내 인라인 포함)' '사격장' 'ATV' '빙벽등반'
 '스키/스노보드']

cat2 name :  음식점
['한식' '일식' '바/까페' '채식전문점' '중식' '서양식' '패밀리레스토랑' '클럽']

cat2 name :  축제
['일반축제' '문화관광축제']

cat2 name :  역사관광지
['유적지/사적지' '성' '안보관광' '사찰' '종교성지' '고택' '고궁' '민속마을' '문' '생가']

cat2 name :  문화시설
['전시관' '미술관/화랑' '박물관' '도서관' '공연장' '기념관' '문화전수시설' '문화원' '외국문화원' '대형서점'
 '영화관' '학교' '컨벤션센터']

cat2 name :  휴양관광지
['관광단지' '공원' '유원지' '온천/욕장/스파' '테마공원' '유람선/잠수함관광' '이색찜질방' '헬스투어']

cat2 name :  숙박시설
['모텔' '한옥스테이' '펜션' '게스트하우스' '홈스테이' '콘도미니엄' '민박' '유스호스텔' '서비스드레지던스']

cat2 name :  공연/행사
['컨벤션' '박람회' '기타행사' '전통공연' '대중콘서트' '연극' '뮤지컬' '클래식음악회']

cat2 name :  쇼핑
['전문상가' '5일장' '상설시장' '공예,공방' '백화점' '면세점' '특산물판매점']

cat2 name :  체험관광지
['이색거리' '농.산.어촌 체험' '이색체험']

cat2 name :  복합 레포츠
['복합 레포츠']

cat2 name :  건축/조형물
['기념탑/기념비/전망대' '유명건물' '동상' '다리/대교' '분수' '터널']

cat2 name :  관광자원
['희귀동.식물' '기암괴석']

cat2 name :  수상 레포츠
['요트' '래프팅' '민물낚시' '바다낚시' '수영' '카약/카누' '윈드서핑/제트스키' '스노쿨링/스킨스쿠버다이빙']

cat2 name :  산업관광지
['기타' '식음료' '발전소']

cat2 name :  항공 레포츠
['스카이다이빙' '헹글라이딩/패러글라이딩']

cat2 name :  레포츠소개
['수상레포츠']

In [7]:
import warnings
warnings.filterwarnings("ignore")

label_df = pd.DataFrame(columns=['cat1','cat2','cat3','count'])
for n_cat1 in df['cat1'].unique() :
    cat2 = df[df['cat1'] == n_cat1]['cat2'].unique()
    for n_cat2 in cat2 :
        cat3  = df[df['cat1'] == n_cat1][df['cat2'] == n_cat2]['cat3'].unique()
        for n_cat3 in cat3 :
            cnt = len(df[df['cat1'] == n_cat1][df['cat2'] == n_cat2][df['cat3'] == n_cat3])
            n = pd.DataFrame([[n_cat1, n_cat2, n_cat3, cnt]], columns=['cat1', 'cat2', 'cat3', 'count'])
            label_df = pd.concat([label_df, n], ignore_index=True)

label_df

    cat1   cat2    cat3 count
0     자연  자연관광지   항구/포구   134
1     자연  자연관광지       섬   111
2     자연  자연관광지   자연휴양림   118
3     자연  자연관광지    해수욕장   207
4     자연  자연관광지       산   239
..   ...    ...     ...   ...
123   쇼핑     쇼핑    상설시장   270
124   쇼핑     쇼핑   공예,공방    41
125   쇼핑     쇼핑     백화점     4
126   쇼핑     쇼핑     면세점     6
127   쇼핑     쇼핑  특산물판매점    37

[128 rows x 4 columns]

- 각각의 cat3가 여러 cat2에 포함되어 있지 않음
    - 카테고리가 겹치 않음
- 최소 2개부터 최대 3000개가 넘는 이미지들이 있음

In [8]:
sorted_label_df = label_df.sort_values(by=['cat1','cat2','cat3'],ascending=True)
sorted_label_df = sorted_label_df.reset_index(drop=True)
display(sorted_label_df)
sorted_label_df = label_df.sort_values(by=['count'],ascending=True)
sorted_label_df = sorted_label_df.reset_index(drop=True)
display(sorted_label_df)

    cat1    cat2    cat3 count
0    레포츠   레포츠소개   수상레포츠    11
1    레포츠  복합 레포츠  복합 레포츠    24
2    레포츠  수상 레포츠     래프팅    18
3    레포츠  수상 레포츠    민물낚시   119
4    레포츠  수상 레포츠    바다낚시    57
..   ...     ...     ...   ...
123   자연   자연관광지      폭포    40
124   자연   자연관광지   항구/포구   134
125   자연   자연관광지    해수욕장   207
126   자연   자연관광지    해안절경    25
127   자연   자연관광지      호수    30

[128 rows x 4 columns]

             cat1    cat2            cat3 count
0             레포츠  육상 레포츠             MTB     2
1             레포츠  항공 레포츠          스카이다이빙     2
2             레포츠  육상 레포츠  인라인(실내 인라인 포함)     2
3    인문(문화/예술/역사)   공연/행사           대중콘서트     2
4    인문(문화/예술/역사)   공연/행사             뮤지컬     2
..            ...     ...             ...   ...
123  인문(문화/예술/역사)      축제            일반축제   549
124  인문(문화/예술/역사)   역사관광지         유적지/사적지   622
125            음식     음식점            바/까페   785
126           레포츠  육상 레포츠       야영장,오토캠핑장  1558
127            음식     음식점              한식  3438

[128 rows x 4 columns]

In [9]:
cat_encoder = {n_cat1 : {} for n_cat1 in df['cat1'].unique()}
for n_cat1 in df['cat1'].unique() : 
    cat2 = df[df['cat1'] == n_cat1]['cat2'].unique()
    
    for n_cat2 in cat2 :
        cat3  = df[df['cat1'] == n_cat1][df['cat2'] == n_cat2]['cat3'].unique()
        cat_encoder[n_cat1][n_cat2] = []
        
        for n_cat3 in cat3 :
            cat_encoder[n_cat1][n_cat2].append(n_cat3)
cat_encoder

{'자연': {'자연관광지': ['항구/포구',
   '섬',
   '자연휴양림',
   '해수욕장',
   '산',
   '수목원',
   '강',
   '자연생태관광지',
   '계곡',
   '폭포',
   '국립공원',
   '해안절경',
   '호수',
   '동굴',
   '도립공원',
   '군립공원',
   '약수터',
   '등대'],
  '관광자원': ['희귀동.식물', '기암괴석']},
 '레포츠': {'육상 레포츠': ['골프',
   '야영장,오토캠핑장',
   '스키(보드) 렌탈샵',
   '자동차경주',
   '자전거하이킹',
   '썰매장',
   '승마',
   '트래킹',
   '수련시설',
   '카지노',
   '번지점프',
   '카트',
   'MTB',
   '스케이트',
   '인라인(실내 인라인 포함)',
   '사격장',
   'ATV',
   '빙벽등반',
   '스키/스노보드'],
  '복합 레포츠': ['복합 레포츠'],
  '수상 레포츠': ['요트',
   '래프팅',
   '민물낚시',
   '바다낚시',
   '수영',
   '카약/카누',
   '윈드서핑/제트스키',
   '스노쿨링/스킨스쿠버다이빙'],
  '항공 레포츠': ['스카이다이빙', '헹글라이딩/패러글라이딩'],
  '레포츠소개': ['수상레포츠']},
 '음식': {'음식점': ['한식', '일식', '바/까페', '채식전문점', '중식', '서양식', '패밀리레스토랑', '클럽']},
 '인문(문화/예술/역사)': {'축제': ['일반축제', '문화관광축제'],
  '역사관광지': ['유적지/사적지',
   '성',
   '안보관광',
   '사찰',
   '종교성지',
   '고택',
   '고궁',
   '민속마을',
   '문',
   '생가'],
  '문화시설': ['전시관',
   '미술관/화랑',
   '박물관',
   '도서관',
   '공연장',
   '기념관',
   '문화전수시설',
   '문화원',
   '외국문화원',
   '대형서점',
   '영화관',
   '학교',
   '컨벤션센터'],
  '휴양관광지': ['관광단지',
   '공원',
   '유원지',
   '온천/욕장/스파',
   '테마공원',
   '유람선/잠수함관광',
   '이색찜질방',
   '헬스투어'],
  '공연/행사': ['컨벤션', '박람회', '기타행사', '전통공연', '대중콘서트', '연극', '뮤지컬', '클래식음악회'],
  '체험관광지': ['이색거리', '농.산.어촌 체험', '이색체험'],
  '건축/조형물': ['기념탑/기념비/전망대', '유명건물', '동상', '다리/대교', '분수', '터널'],
  '산업관광지': ['기타', '식음료', '발전소']},
 '숙박': {'숙박시설': ['모텔',
   '한옥스테이',
   '펜션',
   '게스트하우스',
   '홈스테이',
   '콘도미니엄',
   '민박',
   '유스호스텔',
   '서비스드레지던스']},
 '쇼핑': {'쇼핑': ['전문상가', '5일장', '상설시장', '공예,공방', '백화점', '면세점', '특산물판매점']}}

In [10]:
import matplotlib.pyplot as plt
from matplotlib import font_manager as fm
path = 'C:/Windows/Fonts/malgun.ttf'
font_name = fm.FontProperties(fname=path).get_name()
plt.rc('font', family=font_name)

import random
import cv2

# 이미지 출력

# lb_df_sort = label_df.sort_values(by=['cat1','cat2', 'cat3'])
# f, axes = plt.subplots(32,4, figsize=(20, 120) )
# axes = axes.flatten()
# for i in range(len(axes)) :
#     cat_key = list(lb_df_sort[['cat1', 'cat2', 'cat3']].iloc[i])
#     img_path = df[df['cat1'] == cat_key[0]][df['cat2'] == cat_key[1]][df['cat3'] == cat_key[2]]['img_path']
#     img = cv2.imread(os.path.join('./data/',img_path.iloc[random.randint(0, len(img_path)-1)]))
#     img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    
#     axes[i].imshow(img)
#     axes[i].set_title('-'.join(cat_key)+f"\n{len(img_path)} 장",size=15)
#     axes[i].set_axis_off()
# plt.subplots_adjust(hspace=0.3)

- cat1이 "인문(문화/예술/역사)"고 cat2가 "공연/행사" 혹은 "축제" 면 이미지가 포스터임
    - OCR 모델을 사용해서 글자부분만 crop한후 embedding 해서 classifier 직전에 합쳐주면 좋을 듯
- "인문(문화/예술/역사)-산업관광지-발전소"의 경우 발전소가 전체 이미지에서 작은 부분만을 차지함
    - 이미지를 확대하거나 잘라내면 안될듯
- cat1의 "자연"을 제외하면 건물 이미지가 굉장히 많음
- cat1의 "자연"과 cat2의 "수상레포츠"는 물이 배경이라 구분하기 힘들듯
- 이미지의 부분적인 정보로는 분류가 힘들듯
    - Global context를 포함시킬 수 있는 모델 사용 -> Transformer 기반으로
    - 작은 Object에도 잘 집중 할 수 있는 모델 사용

# Label Encoder

In [43]:
cat1_encoder = {k:i for i, k in enumerate(cat_encoder.keys())}
cat1_encoder

{'자연': 0, '레포츠': 1, '음식': 2, '인문(문화/예술/역사)': 3, '숙박': 4, '쇼핑': 5}

In [44]:
cat2_encoder = []
for cat1_k in cat_encoder.keys() :
    cat2_encoder.append({cat2_k : i for i, cat2_k in enumerate(cat_encoder[cat1_k].keys())})
cat2_encoder

[{'자연관광지': 0, '관광자원': 1},
 {'육상 레포츠': 0, '복합 레포츠': 1, '수상 레포츠': 2, '항공 레포츠': 3, '레포츠소개': 4},
 {'음식점': 0},
 {'축제': 0,
  '역사관광지': 1,
  '문화시설': 2,
  '휴양관광지': 3,
  '공연/행사': 4,
  '체험관광지': 5,
  '건축/조형물': 6,
  '산업관광지': 7},
 {'숙박시설': 0},
 {'쇼핑': 0}]

In [47]:
cat3_encoder = []
for cat1_k in cat_encoder.keys() :
    for i, cat2_k in enumerate(cat_encoder[cat1_k].keys()) :
        cat3_encoder.append({cat3_k : i for i, cat3_k in enumerate(cat_encoder[cat1_k][cat2_k])})
cat3_encoder

[{'항구/포구': 0,
  '섬': 1,
  '자연휴양림': 2,
  '해수욕장': 3,
  '산': 4,
  '수목원': 5,
  '강': 6,
  '자연생태관광지': 7,
  '계곡': 8,
  '폭포': 9,
  '국립공원': 10,
  '해안절경': 11,
  '호수': 12,
  '동굴': 13,
  '도립공원': 14,
  '군립공원': 15,
  '약수터': 16,
  '등대': 17},
 {'희귀동.식물': 0, '기암괴석': 1},
 {'골프': 0,
  '야영장,오토캠핑장': 1,
  '스키(보드) 렌탈샵': 2,
  '자동차경주': 3,
  '자전거하이킹': 4,
  '썰매장': 5,
  '승마': 6,
  '트래킹': 7,
  '수련시설': 8,
  '카지노': 9,
  '번지점프': 10,
  '카트': 11,
  'MTB': 12,
  '스케이트': 13,
  '인라인(실내 인라인 포함)': 14,
  '사격장': 15,
  'ATV': 16,
  '빙벽등반': 17,
  '스키/스노보드': 18},
 {'복합 레포츠': 0},
 {'요트': 0,
  '래프팅': 1,
  '민물낚시': 2,
  '바다낚시': 3,
  '수영': 4,
  '카약/카누': 5,
  '윈드서핑/제트스키': 6,
  '스노쿨링/스킨스쿠버다이빙': 7},
 {'스카이다이빙': 0, '헹글라이딩/패러글라이딩': 1},
 {'수상레포츠': 0},
 {'한식': 0,
  '일식': 1,
  '바/까페': 2,
  '채식전문점': 3,
  '중식': 4,
  '서양식': 5,
  '패밀리레스토랑': 6,
  '클럽': 7},
 {'일반축제': 0, '문화관광축제': 1},
 {'유적지/사적지': 0,
  '성': 1,
  '안보관광': 2,
  '사찰': 3,
  '종교성지': 4,
  '고택': 5,
  '고궁': 6,
  '민속마을': 7,
  '문': 8,
  '생가': 9},
 {'전시관': 0,
  '미술관/화랑': 1,
  '박물관': 2,
  '도서관': 3,
  '공연장': 4,
  '기념관': 5,
  '문화전수시설': 6,
  '문화원': 7,
  '외국문화원': 8,
  '대형서점': 9,
  '영화관': 10,
  '학교': 11,
  '컨벤션센터': 12},
 {'관광단지': 0,
  '공원': 1,
  '유원지': 2,
  '온천/욕장/스파': 3,
  '테마공원': 4,
  '유람선/잠수함관광': 5,
  '이색찜질방': 6,
  '헬스투어': 7},
 {'컨벤션': 0,
  '박람회': 1,
  '기타행사': 2,
  '전통공연': 3,
  '대중콘서트': 4,
  '연극': 5,
  '뮤지컬': 6,
  '클래식음악회': 7},
 {'이색거리': 0, '농.산.어촌 체험': 1, '이색체험': 2},
 {'기념탑/기념비/전망대': 0, '유명건물': 1, '동상': 2, '다리/대교': 3, '분수': 4, '터널': 5},
 {'기타': 0, '식음료': 1, '발전소': 2},
 {'모텔': 0,
  '한옥스테이': 1,
  '펜션': 2,
  '게스트하우스': 3,
  '홈스테이': 4,
  '콘도미니엄': 5,
  '민박': 6,
  '유스호스텔': 7,
  '서비스드레지던스': 8},
 {'전문상가': 0, '5일장': 1, '상설시장': 2, '공예,공방': 3, '백화점': 4, '면세점': 5, '특산물판매점': 6}]

In [33]:
cat1_encoder = [0, 1, 5, 2, 14, 15]

In [32]:
cat2_encoder = []
cnt = 0
for cat1_k in cat_encoder.keys():
    cat2 = {}
    for i, cat2_k in enumerate(cat_encoder[cat1_k].keys()) :
        cat2[i] = cnt
        cnt += 1
    cat2_encoder.append(cat2)
cat2_encoder

[{0: 0, 1: 1},
 {0: 2, 1: 3, 2: 4, 3: 5, 4: 6},
 {0: 7},
 {0: 8, 1: 9, 2: 10, 3: 11, 4: 12, 5: 13, 6: 14, 7: 15},
 {0: 16},
 {0: 17}]

In [16]:
cat3_encoder = []
cnt = 0
for cat1_k in cat_encoder.keys():
    for i, cat2_k in enumerate(cat_encoder[cat1_k].keys()):
        cat3 = {}
        for j, cat3_k in enumerate(cat_encoder[cat1_k][cat2_k]) :
            cat3[j] = cnt
            cnt+=1
        cat3_encoder.append(cat3)
cat3_encoder

[{0: 0,
  1: 1,
  2: 2,
  3: 3,
  4: 4,
  5: 5,
  6: 6,
  7: 7,
  8: 8,
  9: 9,
  10: 10,
  11: 11,
  12: 12,
  13: 13,
  14: 14,
  15: 15,
  16: 16,
  17: 17},
 {0: 18, 1: 19},
 {0: 20,
  1: 21,
  2: 22,
  3: 23,
  4: 24,
  5: 25,
  6: 26,
  7: 27,
  8: 28,
  9: 29,
  10: 30,
  11: 31,
  12: 32,
  13: 33,
  14: 34,
  15: 35,
  16: 36,
  17: 37,
  18: 38},
 {0: 39},
 {0: 40, 1: 41, 2: 42, 3: 43, 4: 44, 5: 45, 6: 46, 7: 47},
 {0: 48, 1: 49},
 {0: 50},
 {0: 51, 1: 52, 2: 53, 3: 54, 4: 55, 5: 56, 6: 57, 7: 58},
 {0: 59, 1: 60},
 {0: 61, 1: 62, 2: 63, 3: 64, 4: 65, 5: 66, 6: 67, 7: 68, 8: 69, 9: 70},
 {0: 71,
  1: 72,
  2: 73,
  3: 74,
  4: 75,
  5: 76,
  6: 77,
  7: 78,
  8: 79,
  9: 80,
  10: 81,
  11: 82,
  12: 83},
 {0: 84, 1: 85, 2: 86, 3: 87, 4: 88, 5: 89, 6: 90, 7: 91},
 {0: 92, 1: 93, 2: 94, 3: 95, 4: 96, 5: 97, 6: 98, 7: 99},
 {0: 100, 1: 101, 2: 102},
 {0: 103, 1: 104, 2: 105, 3: 106, 4: 107, 5: 108},
 {0: 109, 1: 110, 2: 111},
 {0: 112, 1: 113, 2: 114, 3: 115, 4: 116, 5: 117, 6: 118, 7: 119, 8: 120},
 {0: 121, 1: 122, 2: 123, 3: 124, 4: 125, 5: 126, 6: 127}]